// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.1
// source: orchestrator.proto

package daemonpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Run mirrors orch.Run. Timestamps are RFC3339 strings. Nullable string fields
// use proto3 optional so the client can distinguish null from empty.
type Run struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId            string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	TaskId               string                 `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status               string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	WorkflowSnapshotRef  string                 `protobuf:"bytes,5,opt,name=workflow_snapshot_ref,json=workflowSnapshotRef,proto3" json:"workflow_snapshot_ref,omitempty"`
	WorkflowSnapshot     string                 `protobuf:"bytes,6,opt,name=workflow_snapshot,json=workflowSnapshot,proto3" json:"workflow_snapshot,omitempty"`
	CurrentStepId        *string                `protobuf:"bytes,7,opt,name=current_step_id,json=currentStepId,proto3,oneof" json:"current_step_id,omitempty"`
	NeedsAttentionReason *string                `protobuf:"bytes,8,opt,name=needs_attention_reason,json=needsAttentionReason,proto3,oneof" json:"needs_attention_reason,omitempty"`
	Error                *string                `protobuf:"bytes,9,opt,name=error,proto3,oneof" json:"error,omitempty"`
	CreatedAt            string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string                 `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	StartedAt            *string                `protobuf:"bytes,12,opt,name=started_at,json=startedAt,proto3,oneof" json:"started_at,omitempty"`
	CompletedAt          *string                `protobuf:"bytes,13,opt,name=completed_at,json=completedAt,proto3,oneof" json:"completed_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Run) Reset() {
	*x = Run{}
	mi := &file_orchestrator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Run) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Run) ProtoMessage() {}

func (x *Run) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Run.ProtoReflect.Descriptor instead.
func (*Run) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{0}
}

func (x *Run) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Run) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Run) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Run) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Run) GetWorkflowSnapshotRef() string {
	if x != nil {
		return x.WorkflowSnapshotRef
	}
	return ""
}

func (x *Run) GetWorkflowSnapshot() string {
	if x != nil {
		return x.WorkflowSnapshot
	}
	return ""
}

func (x *Run) GetCurrentStepId() string {
	if x != nil && x.CurrentStepId != nil {
		return *x.CurrentStepId
	}
	return ""
}

func (x *Run) GetNeedsAttentionReason() string {
	if x != nil && x.NeedsAttentionReason != nil {
		return *x.NeedsAttentionReason
	}
	return ""
}

func (x *Run) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *Run) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Run) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Run) GetStartedAt() string {
	if x != nil && x.StartedAt != nil {
		return *x.StartedAt
	}
	return ""
}

func (x *Run) GetCompletedAt() string {
	if x != nil && x.CompletedAt != nil {
		return *x.CompletedAt
	}
	return ""
}

type CreateRunRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ProjectId           string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	TaskId              string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	WorkflowSnapshotRef string                 `protobuf:"bytes,3,opt,name=workflow_snapshot_ref,json=workflowSnapshotRef,proto3" json:"workflow_snapshot_ref,omitempty"`
	WorkflowSnapshot    string                 `protobuf:"bytes,4,opt,name=workflow_snapshot,json=workflowSnapshot,proto3" json:"workflow_snapshot,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateRunRequest) Reset() {
	*x = CreateRunRequest{}
	mi := &file_orchestrator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRunRequest) ProtoMessage() {}

func (x *CreateRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRunRequest.ProtoReflect.Descriptor instead.
func (*CreateRunRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRunRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreateRunRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CreateRunRequest) GetWorkflowSnapshotRef() string {
	if x != nil {
		return x.WorkflowSnapshotRef
	}
	return ""
}

func (x *CreateRunRequest) GetWorkflowSnapshot() string {
	if x != nil {
		return x.WorkflowSnapshot
	}
	return ""
}

type GetRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRunRequest) Reset() {
	*x = GetRunRequest{}
	mi := &file_orchestrator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRunRequest) ProtoMessage() {}

func (x *GetRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRunRequest.ProtoReflect.Descriptor instead.
func (*GetRunRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{2}
}

func (x *GetRunRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListRunsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// When set, only runs for this project are returned.
	ProjectId     *string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3,oneof" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunsRequest) Reset() {
	*x = ListRunsRequest{}
	mi := &file_orchestrator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunsRequest) ProtoMessage() {}

func (x *ListRunsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunsRequest.ProtoReflect.Descriptor instead.
func (*ListRunsRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{3}
}

func (x *ListRunsRequest) GetProjectId() string {
	if x != nil && x.ProjectId != nil {
		return *x.ProjectId
	}
	return ""
}

type ListRunsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Runs          []*Run                 `protobuf:"bytes,1,rep,name=runs,proto3" json:"runs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunsResponse) Reset() {
	*x = ListRunsResponse{}
	mi := &file_orchestrator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunsResponse) ProtoMessage() {}

func (x *ListRunsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunsResponse.ProtoReflect.Descriptor instead.
func (*ListRunsResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{4}
}

func (x *ListRunsResponse) GetRuns() []*Run {
	if x != nil {
		return x.Runs
	}
	return nil
}

type HumanInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	StepAttemptId string                 `protobuf:"bytes,3,opt,name=step_attempt_id,json=stepAttemptId,proto3" json:"step_attempt_id,omitempty"`
	ExecutionId   *string                `protobuf:"bytes,4,opt,name=execution_id,json=executionId,proto3,oneof" json:"execution_id,omitempty"`
	Prompt        string                 `protobuf:"bytes,5,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Response      *string                `protobuf:"bytes,6,opt,name=response,proto3,oneof" json:"response,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	AnsweredAt    *string                `protobuf:"bytes,9,opt,name=answered_at,json=answeredAt,proto3,oneof" json:"answered_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HumanInput) Reset() {
	*x = HumanInput{}
	mi := &file_orchestrator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HumanInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HumanInput) ProtoMessage() {}

func (x *HumanInput) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HumanInput.ProtoReflect.Descriptor instead.
func (*HumanInput) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{5}
}

func (x *HumanInput) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HumanInput) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *HumanInput) GetStepAttemptId() string {
	if x != nil {
		return x.StepAttemptId
	}
	return ""
}

func (x *HumanInput) GetExecutionId() string {
	if x != nil && x.ExecutionId != nil {
		return *x.ExecutionId
	}
	return ""
}

func (x *HumanInput) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *HumanInput) GetResponse() string {
	if x != nil && x.Response != nil {
		return *x.Response
	}
	return ""
}

func (x *HumanInput) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HumanInput) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *HumanInput) GetAnsweredAt() string {
	if x != nil && x.AnsweredAt != nil {
		return *x.AnsweredAt
	}
	return ""
}

type ListHumanInputsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// When set, only human inputs for this run are returned; otherwise all
	// rows in the store are listed.
	RunId         *string `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3,oneof" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHumanInputsRequest) Reset() {
	*x = ListHumanInputsRequest{}
	mi := &file_orchestrator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHumanInputsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHumanInputsRequest) ProtoMessage() {}

func (x *ListHumanInputsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHumanInputsRequest.ProtoReflect.Descriptor instead.
func (*ListHumanInputsRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{6}
}

func (x *ListHumanInputsRequest) GetRunId() string {
	if x != nil && x.RunId != nil {
		return *x.RunId
	}
	return ""
}

type ListHumanInputsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HumanInputs   []*HumanInput          `protobuf:"bytes,1,rep,name=human_inputs,json=humanInputs,proto3" json:"human_inputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHumanInputsResponse) Reset() {
	*x = ListHumanInputsResponse{}
	mi := &file_orchestrator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHumanInputsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHumanInputsResponse) ProtoMessage() {}

func (x *ListHumanInputsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHumanInputsResponse.ProtoReflect.Descriptor instead.
func (*ListHumanInputsResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{7}
}

func (x *ListHumanInputsResponse) GetHumanInputs() []*HumanInput {
	if x != nil {
		return x.HumanInputs
	}
	return nil
}

type AnswerHumanInputRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Response      string                 `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerHumanInputRequest) Reset() {
	*x = AnswerHumanInputRequest{}
	mi := &file_orchestrator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerHumanInputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerHumanInputRequest) ProtoMessage() {}

func (x *AnswerHumanInputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerHumanInputRequest.ProtoReflect.Descriptor instead.
func (*AnswerHumanInputRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{8}
}

func (x *AnswerHumanInputRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AnswerHumanInputRequest) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type RetryRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryRunRequest) Reset() {
	*x = RetryRunRequest{}
	mi := &file_orchestrator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryRunRequest) ProtoMessage() {}

func (x *RetryRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryRunRequest.ProtoReflect.Descriptor instead.
func (*RetryRunRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{9}
}

func (x *RetryRunRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CancelRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRunRequest) Reset() {
	*x = CancelRunRequest{}
	mi := &file_orchestrator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRunRequest) ProtoMessage() {}

func (x *CancelRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRunRequest.ProtoReflect.Descriptor instead.
func (*CancelRunRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{10}
}

func (x *CancelRunRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Execution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	StepAttemptId string                 `protobuf:"bytes,3,opt,name=step_attempt_id,json=stepAttemptId,proto3" json:"step_attempt_id,omitempty"`
	Kind          string                 `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	PaneId        *string                `protobuf:"bytes,6,opt,name=pane_id,json=paneId,proto3,oneof" json:"pane_id,omitempty"`
	ProcessId     *string                `protobuf:"bytes,7,opt,name=process_id,json=processId,proto3,oneof" json:"process_id,omitempty"`
	PromptRef     string                 `protobuf:"bytes,8,opt,name=prompt_ref,json=promptRef,proto3" json:"prompt_ref,omitempty"`
	PromptHash    string                 `protobuf:"bytes,9,opt,name=prompt_hash,json=promptHash,proto3" json:"prompt_hash,omitempty"`
	ResultJson    *string                `protobuf:"bytes,10,opt,name=result_json,json=resultJson,proto3,oneof" json:"result_json,omitempty"`
	ResultCommit  *string                `protobuf:"bytes,11,opt,name=result_commit,json=resultCommit,proto3,oneof" json:"result_commit,omitempty"`
	Error         *string                `protobuf:"bytes,12,opt,name=error,proto3,oneof" json:"error,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	StartedAt     *string                `protobuf:"bytes,15,opt,name=started_at,json=startedAt,proto3,oneof" json:"started_at,omitempty"`
	CompletedAt   *string                `protobuf:"bytes,16,opt,name=completed_at,json=completedAt,proto3,oneof" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Execution) Reset() {
	*x = Execution{}
	mi := &file_orchestrator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Execution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Execution) ProtoMessage() {}

func (x *Execution) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Execution.ProtoReflect.Descriptor instead.
func (*Execution) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{11}
}

func (x *Execution) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Execution) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *Execution) GetStepAttemptId() string {
	if x != nil {
		return x.StepAttemptId
	}
	return ""
}

func (x *Execution) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Execution) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Execution) GetPaneId() string {
	if x != nil && x.PaneId != nil {
		return *x.PaneId
	}
	return ""
}

func (x *Execution) GetProcessId() string {
	if x != nil && x.ProcessId != nil {
		return *x.ProcessId
	}
	return ""
}

func (x *Execution) GetPromptRef() string {
	if x != nil {
		return x.PromptRef
	}
	return ""
}

func (x *Execution) GetPromptHash() string {
	if x != nil {
		return x.PromptHash
	}
	return ""
}

func (x *Execution) GetResultJson() string {
	if x != nil && x.ResultJson != nil {
		return *x.ResultJson
	}
	return ""
}

func (x *Execution) GetResultCommit() string {
	if x != nil && x.ResultCommit != nil {
		return *x.ResultCommit
	}
	return ""
}

func (x *Execution) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *Execution) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Execution) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Execution) GetStartedAt() string {
	if x != nil && x.StartedAt != nil {
		return *x.StartedAt
	}
	return ""
}

func (x *Execution) GetCompletedAt() string {
	if x != nil && x.CompletedAt != nil {
		return *x.CompletedAt
	}
	return ""
}

type Artifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ExecutionId   string                 `protobuf:"bytes,2,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Hash          string                 `protobuf:"bytes,5,opt,name=hash,proto3" json:"hash,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Artifact) Reset() {
	*x = Artifact{}
	mi := &file_orchestrator_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artifact) ProtoMessage() {}

func (x *Artifact) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artifact.ProtoReflect.Descriptor instead.
func (*Artifact) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{12}
}

func (x *Artifact) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Artifact) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *Artifact) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Artifact) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Artifact) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Artifact) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type InspectExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectExecutionRequest) Reset() {
	*x = InspectExecutionRequest{}
	mi := &file_orchestrator_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectExecutionRequest) ProtoMessage() {}

func (x *InspectExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectExecutionRequest.ProtoReflect.Descriptor instead.
func (*InspectExecutionRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{13}
}

func (x *InspectExecutionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type InspectExecutionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Execution     *Execution             `protobuf:"bytes,1,opt,name=execution,proto3" json:"execution,omitempty"`
	Artifacts     []*Artifact            `protobuf:"bytes,2,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectExecutionResponse) Reset() {
	*x = InspectExecutionResponse{}
	mi := &file_orchestrator_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectExecutionResponse) ProtoMessage() {}

func (x *InspectExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectExecutionResponse.ProtoReflect.Descriptor instead.
func (*InspectExecutionResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{14}
}

func (x *InspectExecutionResponse) GetExecution() *Execution {
	if x != nil {
		return x.Execution
	}
	return nil
}

func (x *InspectExecutionResponse) GetArtifacts() []*Artifact {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

type StreamEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	RunId string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	// Only events with seq > after_seq are streamed. Use 0 to replay from the
	// beginning of the run.
	AfterSeq      int64 `protobuf:"varint,2,opt,name=after_seq,json=afterSeq,proto3" json:"after_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsRequest) Reset() {
	*x = StreamEventsRequest{}
	mi := &file_orchestrator_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsRequest) ProtoMessage() {}

func (x *StreamEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamEventsRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{15}
}

func (x *StreamEventsRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *StreamEventsRequest) GetAfterSeq() int64 {
	if x != nil {
		return x.AfterSeq
	}
	return 0
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RunId         *string                `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3,oneof" json:"run_id,omitempty"`
	Seq           int64                  `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Payload       string                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_orchestrator_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{16}
}

func (x *Event) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Event) GetRunId() string {
	if x != nil && x.RunId != nil {
		return *x.RunId
	}
	return ""
}

func (x *Event) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *Event) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_orchestrator_proto protoreflect.FileDescriptor

const file_orchestrator_proto_rawDesc = "" +
	"\n" +
	"\x12orchestrator.proto\x12\x0fbdtui.daemon.v1\"\xac\x04\n" +
	"\x03Run\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x122\n" +
	"\x15workflow_snapshot_ref\x18\x05 \x01(\tR\x13workflowSnapshotRef\x12+\n" +
	"\x11workflow_snapshot\x18\x06 \x01(\tR\x10workflowSnapshot\x12+\n" +
	"\x0fcurrent_step_id\x18\a \x01(\tH\x00R\rcurrentStepId\x88\x01\x01\x129\n" +
	"\x16needs_attention_reason\x18\b \x01(\tH\x01R\x14needsAttentionReason\x88\x01\x01\x12\x19\n" +
	"\x05error\x18\t \x01(\tH\x02R\x05error\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\tR\tupdatedAt\x12\"\n" +
	"\n" +
	"started_at\x18\f \x01(\tH\x03R\tstartedAt\x88\x01\x01\x12&\n" +
	"\fcompleted_at\x18\r \x01(\tH\x04R\vcompletedAt\x88\x01\x01B\x12\n" +
	"\x10_current_step_idB\x19\n" +
	"\x17_needs_attention_reasonB\b\n" +
	"\x06_errorB\r\n" +
	"\v_started_atB\x0f\n" +
	"\r_completed_at\"\xab\x01\n" +
	"\x10CreateRunRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x122\n" +
	"\x15workflow_snapshot_ref\x18\x03 \x01(\tR\x13workflowSnapshotRef\x12+\n" +
	"\x11workflow_snapshot\x18\x04 \x01(\tR\x10workflowSnapshot\"\x1f\n" +
	"\rGetRunRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"D\n" +
	"\x0fListRunsRequest\x12\"\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tH\x00R\tprojectId\x88\x01\x01B\r\n" +
	"\v_project_id\"<\n" +
	"\x10ListRunsResponse\x12(\n" +
	"\x04runs\x18\x01 \x03(\v2\x14.bdtui.daemon.v1.RunR\x04runs\"\xc7\x02\n" +
	"\n" +
	"HumanInput\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12&\n" +
	"\x0fstep_attempt_id\x18\x03 \x01(\tR\rstepAttemptId\x12&\n" +
	"\fexecution_id\x18\x04 \x01(\tH\x00R\vexecutionId\x88\x01\x01\x12\x16\n" +
	"\x06prompt\x18\x05 \x01(\tR\x06prompt\x12\x1f\n" +
	"\bresponse\x18\x06 \x01(\tH\x01R\bresponse\x88\x01\x01\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12$\n" +
	"\vanswered_at\x18\t \x01(\tH\x02R\n" +
	"answeredAt\x88\x01\x01B\x0f\n" +
	"\r_execution_idB\v\n" +
	"\t_responseB\x0e\n" +
	"\f_answered_at\"?\n" +
	"\x16ListHumanInputsRequest\x12\x1a\n" +
	"\x06run_id\x18\x01 \x01(\tH\x00R\x05runId\x88\x01\x01B\t\n" +
	"\a_run_id\"Y\n" +
	"\x17ListHumanInputsResponse\x12>\n" +
	"\fhuman_inputs\x18\x01 \x03(\v2\x1b.bdtui.daemon.v1.HumanInputR\vhumanInputs\"E\n" +
	"\x17AnswerHumanInputRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bresponse\x18\x02 \x01(\tR\bresponse\"!\n" +
	"\x0fRetryRunRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\"\n" +
	"\x10CancelRunRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xe4\x04\n" +
	"\tExecution\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12&\n" +
	"\x0fstep_attempt_id\x18\x03 \x01(\tR\rstepAttemptId\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1c\n" +
	"\apane_id\x18\x06 \x01(\tH\x00R\x06paneId\x88\x01\x01\x12\"\n" +
	"\n" +
	"process_id\x18\a \x01(\tH\x01R\tprocessId\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"prompt_ref\x18\b \x01(\tR\tpromptRef\x12\x1f\n" +
	"\vprompt_hash\x18\t \x01(\tR\n" +
	"promptHash\x12$\n" +
	"\vresult_json\x18\n" +
	" \x01(\tH\x02R\n" +
	"resultJson\x88\x01\x01\x12(\n" +
	"\rresult_commit\x18\v \x01(\tH\x03R\fresultCommit\x88\x01\x01\x12\x19\n" +
	"\x05error\x18\f \x01(\tH\x04R\x05error\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_at\x18\r \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\tR\tupdatedAt\x12\"\n" +
	"\n" +
	"started_at\x18\x0f \x01(\tH\x05R\tstartedAt\x88\x01\x01\x12&\n" +
	"\fcompleted_at\x18\x10 \x01(\tH\x06R\vcompletedAt\x88\x01\x01B\n" +
	"\n" +
	"\b_pane_idB\r\n" +
	"\v_process_idB\x0e\n" +
	"\f_result_jsonB\x10\n" +
	"\x0e_result_commitB\b\n" +
	"\x06_errorB\r\n" +
	"\v_started_atB\x0f\n" +
	"\r_completed_at\"\x98\x01\n" +
	"\bArtifact\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fexecution_id\x18\x02 \x01(\tR\vexecutionId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x12\n" +
	"\x04hash\x18\x05 \x01(\tR\x04hash\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\")\n" +
	"\x17InspectExecutionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x8d\x01\n" +
	"\x18InspectExecutionResponse\x128\n" +
	"\texecution\x18\x01 \x01(\v2\x1a.bdtui.daemon.v1.ExecutionR\texecution\x127\n" +
	"\tartifacts\x18\x02 \x03(\v2\x19.bdtui.daemon.v1.ArtifactR\tartifacts\"I\n" +
	"\x13StreamEventsRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1b\n" +
	"\tafter_seq\x18\x02 \x01(\x03R\bafterSeq\"\x9d\x01\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\x06run_id\x18\x02 \x01(\tH\x00R\x05runId\x88\x01\x01\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x03R\x03seq\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x05 \x01(\tR\apayload\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAtB\t\n" +
	"\a_run_id2\xe9\x05\n" +
	"\fOrchestrator\x12D\n" +
	"\tCreateRun\x12!.bdtui.daemon.v1.CreateRunRequest\x1a\x14.bdtui.daemon.v1.Run\x12O\n" +
	"\bListRuns\x12 .bdtui.daemon.v1.ListRunsRequest\x1a!.bdtui.daemon.v1.ListRunsResponse\x12>\n" +
	"\x06GetRun\x12\x1e.bdtui.daemon.v1.GetRunRequest\x1a\x14.bdtui.daemon.v1.Run\x12d\n" +
	"\x0fListHumanInputs\x12'.bdtui.daemon.v1.ListHumanInputsRequest\x1a(.bdtui.daemon.v1.ListHumanInputsResponse\x12Y\n" +
	"\x10AnswerHumanInput\x12(.bdtui.daemon.v1.AnswerHumanInputRequest\x1a\x1b.bdtui.daemon.v1.HumanInput\x12B\n" +
	"\bRetryRun\x12 .bdtui.daemon.v1.RetryRunRequest\x1a\x14.bdtui.daemon.v1.Run\x12D\n" +
	"\tCancelRun\x12!.bdtui.daemon.v1.CancelRunRequest\x1a\x14.bdtui.daemon.v1.Run\x12g\n" +
	"\x10InspectExecution\x12(.bdtui.daemon.v1.InspectExecutionRequest\x1a).bdtui.daemon.v1.InspectExecutionResponse\x12N\n" +
	"\fStreamEvents\x12$.bdtui.daemon.v1.StreamEventsRequest\x1a\x16.bdtui.daemon.v1.Event0\x01B)Z'bdtui/internal/daemon/daemonpb;daemonpbb\x06proto3"

var (
	file_orchestrator_proto_rawDescOnce sync.Once
	file_orchestrator_proto_rawDescData []byte
)

func file_orchestrator_proto_rawDescGZIP() []byte {
	file_orchestrator_proto_rawDescOnce.Do(func() {
		file_orchestrator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orchestrator_proto_rawDesc), len(file_orchestrator_proto_rawDesc)))
	})
	return file_orchestrator_proto_rawDescData
}

var file_orchestrator_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_orchestrator_proto_goTypes = []any{
	(*Run)(nil),                      // 0: bdtui.daemon.v1.Run
	(*CreateRunRequest)(nil),         // 1: bdtui.daemon.v1.CreateRunRequest
	(*GetRunRequest)(nil),            // 2: bdtui.daemon.v1.GetRunRequest
	(*ListRunsRequest)(nil),          // 3: bdtui.daemon.v1.ListRunsRequest
	(*ListRunsResponse)(nil),         // 4: bdtui.daemon.v1.ListRunsResponse
	(*HumanInput)(nil),               // 5: bdtui.daemon.v1.HumanInput
	(*ListHumanInputsRequest)(nil),   // 6: bdtui.daemon.v1.ListHumanInputsRequest
	(*ListHumanInputsResponse)(nil),  // 7: bdtui.daemon.v1.ListHumanInputsResponse
	(*AnswerHumanInputRequest)(nil),  // 8: bdtui.daemon.v1.AnswerHumanInputRequest
	(*RetryRunRequest)(nil),          // 9: bdtui.daemon.v1.RetryRunRequest
	(*CancelRunRequest)(nil),         // 10: bdtui.daemon.v1.CancelRunRequest
	(*Execution)(nil),                // 11: bdtui.daemon.v1.Execution
	(*Artifact)(nil),                 // 12: bdtui.daemon.v1.Artifact
	(*InspectExecutionRequest)(nil),  // 13: bdtui.daemon.v1.InspectExecutionRequest
	(*InspectExecutionResponse)(nil), // 14: bdtui.daemon.v1.InspectExecutionResponse
	(*StreamEventsRequest)(nil),      // 15: bdtui.daemon.v1.StreamEventsRequest
	(*Event)(nil),                    // 16: bdtui.daemon.v1.Event
}
var file_orchestrator_proto_depIdxs = []int32{
	0,  // 0: bdtui.daemon.v1.ListRunsResponse.runs:type_name -> bdtui.daemon.v1.Run
	5,  // 1: bdtui.daemon.v1.ListHumanInputsResponse.human_inputs:type_name -> bdtui.daemon.v1.HumanInput
	11, // 2: bdtui.daemon.v1.InspectExecutionResponse.execution:type_name -> bdtui.daemon.v1.Execution
	12, // 3: bdtui.daemon.v1.InspectExecutionResponse.artifacts:type_name -> bdtui.daemon.v1.Artifact
	1,  // 4: bdtui.daemon.v1.Orchestrator.CreateRun:input_type -> bdtui.daemon.v1.CreateRunRequest
	3,  // 5: bdtui.daemon.v1.Orchestrator.ListRuns:input_type -> bdtui.daemon.v1.ListRunsRequest
	2,  // 6: bdtui.daemon.v1.Orchestrator.GetRun:input_type -> bdtui.daemon.v1.GetRunRequest
	6,  // 7: bdtui.daemon.v1.Orchestrator.ListHumanInputs:input_type -> bdtui.daemon.v1.ListHumanInputsRequest
	8,  // 8: bdtui.daemon.v1.Orchestrator.AnswerHumanInput:input_type -> bdtui.daemon.v1.AnswerHumanInputRequest
	9,  // 9: bdtui.daemon.v1.Orchestrator.RetryRun:input_type -> bdtui.daemon.v1.RetryRunRequest
	10, // 10: bdtui.daemon.v1.Orchestrator.CancelRun:input_type -> bdtui.daemon.v1.CancelRunRequest
	13, // 11: bdtui.daemon.v1.Orchestrator.InspectExecution:input_type -> bdtui.daemon.v1.InspectExecutionRequest
	15, // 12: bdtui.daemon.v1.Orchestrator.StreamEvents:input_type -> bdtui.daemon.v1.StreamEventsRequest
	0,  // 13: bdtui.daemon.v1.Orchestrator.CreateRun:output_type -> bdtui.daemon.v1.Run
	4,  // 14: bdtui.daemon.v1.Orchestrator.ListRuns:output_type -> bdtui.daemon.v1.ListRunsResponse
	0,  // 15: bdtui.daemon.v1.Orchestrator.GetRun:output_type -> bdtui.daemon.v1.Run
	7,  // 16: bdtui.daemon.v1.Orchestrator.ListHumanInputs:output_type -> bdtui.daemon.v1.ListHumanInputsResponse
	5,  // 17: bdtui.daemon.v1.Orchestrator.AnswerHumanInput:output_type -> bdtui.daemon.v1.HumanInput
	0,  // 18: bdtui.daemon.v1.Orchestrator.RetryRun:output_type -> bdtui.daemon.v1.Run
	0,  // 19: bdtui.daemon.v1.Orchestrator.CancelRun:output_type -> bdtui.daemon.v1.Run
	14, // 20: bdtui.daemon.v1.Orchestrator.InspectExecution:output_type -> bdtui.daemon.v1.InspectExecutionResponse
	16, // 21: bdtui.daemon.v1.Orchestrator.StreamEvents:output_type -> bdtui.daemon.v1.Event
	13, // [13:22] is the sub-list for method output_type
	4,  // [4:13] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_orchestrator_proto_init() }
func file_orchestrator_proto_init() {
	if File_orchestrator_proto != nil {
		return
	}
	file_orchestrator_proto_msgTypes[0].OneofWrappers = []any{}
	file_orchestrator_proto_msgTypes[3].OneofWrappers = []any{}
	file_orchestrator_proto_msgTypes[5].OneofWrappers = []any{}
	file_orchestrator_proto_msgTypes[6].OneofWrappers = []any{}
	file_orchestrator_proto_msgTypes[11].OneofWrappers = []any{}
	file_orchestrator_proto_msgTypes[16].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orchestrator_proto_rawDesc), len(file_orchestrator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orchestrator_proto_goTypes,
		DependencyIndexes: file_orchestrator_proto_depIdxs,
		MessageInfos:      file_orchestrator_proto_msgTypes,
	}.Build()
	File_orchestrator_proto = out.File
	file_orchestrator_proto_goTypes = nil
	file_orchestrator_proto_depIdxs = nil
}
